### ISSUE TITLE
Tools and Scripts Not Found

### ISSUE THREAD

**Issue by ghost** [pestrela/dj_kb#1]
Love the guide, thanks for writing this all up. I am trying to find your python scripts for ID3 tagging and cue copying but it seems they are no longer available. Is this intentional? Are they accessible somewhere else?

**Comment by pestrela** [comment]
HI Marcus
the scripts are in the old location:
https://github.com/pestrela/music/tree/master/traktor/tools_traktor

Indeed I've split the repo because the old one was way too large

really curious how you use these tools and any feedback/requests

**Comment by ghost** [comment]
Thanks a lot. 

My plan is to use your mp3tag tools to write the id3 tags based on folder because I want to use your folder based organization method.
I use Serato instead of Traktor which stores the cues inside the ID3 tag so I'm hoping to use some of your tools to help me write a script to keep those file's tags up to date if I have them in multiple places.
